//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceLibrary1")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IGestorUsuario")]
    public interface IGestorUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorUsuario/existe", ReplyAction="http://tempuri.org/IGestorUsuario/existeResponse")]
        bool existe(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorUsuario/buscarUsuario", ReplyAction="http://tempuri.org/IGestorUsuario/buscarUsuarioResponse")]
        Practica2.ServiceReference1.Usuario buscarUsuario(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorUsuario/agregarUsuario", ReplyAction="http://tempuri.org/IGestorUsuario/agregarUsuarioResponse")]
        void agregarUsuario(string user, string password, int tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorUsuario/guardarUsuarios", ReplyAction="http://tempuri.org/IGestorUsuario/guardarUsuariosResponse")]
        void guardarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestorUsuario/imprimirUsuarios", ReplyAction="http://tempuri.org/IGestorUsuario/imprimirUsuariosResponse")]
        void imprimirUsuarios();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestorUsuarioChannel : Practica2.ServiceReference1.IGestorUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestorUsuarioClient : System.ServiceModel.ClientBase<Practica2.ServiceReference1.IGestorUsuario>, Practica2.ServiceReference1.IGestorUsuario {
        
        public GestorUsuarioClient() {
        }
        
        public GestorUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestorUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestorUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestorUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool existe(string user) {
            return base.Channel.existe(user);
        }
        
        public Practica2.ServiceReference1.Usuario buscarUsuario(string user) {
            return base.Channel.buscarUsuario(user);
        }
        
        public void agregarUsuario(string user, string password, int tipo) {
            base.Channel.agregarUsuario(user, password, tipo);
        }
        
        public void guardarUsuarios() {
            base.Channel.guardarUsuarios();
        }
        
        public void imprimirUsuarios() {
            base.Channel.imprimirUsuarios();
        }
    }
}
